version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
      KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/kafka/config/zoo-jaas.conf -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider"
    volumes:
      - ./testHelpers/kafka/zoo-jaas.conf:/opt/kafka/config/zoo-jaas.conf

  zoonavigator:
    container_name: zoonavigator
    image: elkozmon/zoonavigator
    ports:
      - 9000:9000


  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    user: root
    labels:
      - "custom.project=kafkajs"
      - "custom.service=kafka"
    depends_on:
      - zookeeper  
    ports:
      - "9095:9095"
    environment:
      KAFKA_ADMIN_CLIENT_CONFIG: admin.client.timeout.ms=5000
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      ALLOW_PLAINTEXT_LISTENER: 'no'
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_SSL:SASL_SSL
      KAFKA_LISTENERS: SASL_SSL://0.0.0.0:9095
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://kafkajs:9095
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_SSL_CLIENT_AUTH: 'required'
      KAFKA_SSL_KEYSTORE_FILENAME: "kafka.server.keystore.jks"
      KAFKA_SSL_KEYSTORE_CREDENTIALS: "keystore_creds"
      KAFKA_SSL_KEY_CREDENTIALS: "sslkey_creds"
      KAFKA_SSL_TRUSTSTORE_FILENAME: "kafka.server.truststore.jks"
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: "truststore_creds"
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "SCRAM-SHA-512"
      KAFKA_SASL_ENABLED_MECHANISMS: "SCRAM-SHA-512"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL
      KAFKA_INTER_BROKER_PROTOCOL: SASL_SSL
      KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/kafka/config/kafka-jaas.conf"
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - ./testHelpers/certs/kafka.server.keystore.jks:/etc/kafka/secrets/kafka.server.keystore.jks
      - ./testHelpers/certs/kafka.server.truststore.jks:/etc/kafka/secrets/kafka.server.truststore.jks
      - ./testHelpers/certs/keystore_creds:/etc/kafka/secrets/keystore_creds
      - ./testHelpers/certs/sslkey_creds:/etc/kafka/secrets/sslkey_creds
      - ./testHelpers/certs/truststore_creds:/etc/kafka/secrets/truststore_creds
      - ./testHelpers/kafka/kafka-jaas.conf:/opt/kafka/config/kafka-jaas.conf
      - ./testHelpers/kafka/client.properties:/opt/kafka/config/client.properties
